[build]
  functions = "functions/"
  command = "npm install && mkdir -p functions && cp src/index.js functions/"

# This is the new, crucial part.
# It adds the required CORS headers to all responses from your function.
[[headers]]
  for = "/.netlify/functions/index/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"